apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdp-networkpolicy-customizer-admission-manager-sa
  labels:
    app: cdp-networkpolicy-customizer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdp-networkpolicy-customizer-admission-manager-cr
  labels:
    app: cdp-networkpolicy-customizer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - pods
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdp-networkpolicy-customizer-admission-manager-crb
  labels:
    app: cdp-networkpolicy-customizer
subjects:
- kind: ServiceAccount
  name: cdp-networkpolicy-customizer-admission-manager-sa
  namespace: cdp-customizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdp-networkpolicy-customizer-admission-manager-cr
