apiVersion: v1
kind: Service
metadata:
  name: cdp-networkpolicy-customizer-admission-manager
  labels:
    app: cdp-networkpolicy-customizer
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cdp-networkpolicy-customizer
